[profile.default]

cache = true

cache_path = 'cache'
evm_version = 'cancun'

libs = ['lib']
names = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
src = 'src'
script = 'script'
test = 'test/unit'

# Allow scripts to write deployment addresses to the app directory
fs_permissions = [{ access = "read-write", path = "./app" }]

[profile.sepolia]
test = "test/sepolia"